"""update payment model for cashfree

Revision ID: 2c20bd38e9eb
Revises: 30f29b71b890
Create Date: 2026-07-22 11:55:12.054346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '2c20bd38e9eb'
down_revision: Union[str, None] = '30f29b71b890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('cashfree_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('payment_session_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('order_currency', sa.String(length=10), nullable=True))
    op.add_column('payments', sa.Column('gateway', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('payment_message', sa.String(length=255), nullable=True))
    op.alter_column('payments', 'transaction_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.create_unique_constraint(None, 'payments', ['cashfree_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'transaction_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('payments', 'payment_message')
    op.drop_column('payments', 'gateway')
    op.drop_column('payments', 'order_currency')
    op.drop_column('payments', 'payment_session_id')
    op.drop_column('payments', 'cashfree_order_id')
    # ### end Alembic commands ###
